In [1]:
import polars as pl
import json

abb = pl.read_csv("abbreviations.csv")
abb = abb.filter(pl.col("abbreviation").is_not_null())

with open("eindeutigeAbk.json", "r", encoding="utf-8") as f:
    data = json.load(f)

lotta_abb = pl.DataFrame(list(data.values())).rename({"Abkuerzung": "abbreviation", "Ausformulierung": "full_word"})
lotta_abb = lotta_abb.join(abb, on="abbreviation", how="left")

left_out = abb.join(lotta_abb, on="abbreviation", how="anti")

In [ ]:
left_out

In [ ]:
left_out.filter(pl.all_horizontal(pl.col("RG1", "RG2", "RG3", "RG4", "RG5", "RG6", "RG7", "RG8", "RG9", "note", "note1", "note2").is_null()))

In [ ]:
left_out.filter(pl.all_horizontal(pl.col("RG1", "RG2", "RG3", "RG4", "RG5", "RG6", "RG7", "RG8", "RG9").is_null()))

In [ ]:
left_out.filter(pl.all_horizontal(pl.col("note1", "note2").is_null()))

In [ ]:
left_out.filter(pl.col("abbreviation").is_null())

# expansion dictionaries

## for all volumes

This one will only keep entries where the expansion is the same for all volumes. It should/could be complemented with one dictionary per volume with the volume-specific expansions.

things to remove

In [28]:
# (fl.) or (fl. vel duc.)
#lotta_abb.filter(pl.col("full_word").str.contains(r"\(fl\.( vel duc.)?\)"))
# (Plural)
lotta_abb.filter(pl.col("full_word").str.contains(r"\(Plural\)"))

shape: (5, 18)
┌─────────────┬────────────┬────────────┬────────────┬───┬───────┬────────────┬───────┬────────────┐
│ abbreviatio ┆ full_word  ┆ full_word_ ┆ translatio ┆ … ┆ RG8   ┆ RG9        ┆ note1 ┆ note2      │
│ n           ┆ ---        ┆ right      ┆ n          ┆   ┆ ---   ┆ ---        ┆ ---   ┆ ---        │
│ ---         ┆ str        ┆ ---        ┆ ---        ┆   ┆ str   ┆ str        ┆ str   ┆ str        │
│ str         ┆            ┆ str        ┆ str        ┆   ┆       ┆            ┆       ┆            │
╞═════════════╪════════════╪════════════╪════════════╪═══╪═══════╪════════════╪═══════╪════════════╡
│ appl.       ┆ apostoli   ┆ apostoli   ┆ die        ┆ … ┆ appl. ┆ appl.      ┆ null  ┆ in den Bd. │
│             ┆ (Plural)   ┆ (Plural)   ┆ Apostel    ┆   ┆       ┆            ┆       ┆ 1, 2, 3    │
│             ┆            ┆            ┆            ┆   ┆       ┆            ┆       ┆ wahrschein │
│             ┆            ┆            ┆            ┆   ┆       ┆            ┆       ┆ l…         │
│ bb.         ┆ beati      ┆ beati      ┆ die        ┆ … ┆ bb.   ┆ bb.        ┆ null  ┆ null       │
│             ┆ (Plural)   ┆ (Plural)   ┆ heiligen   ┆   ┆       ┆            ┆       ┆            │
│ dd.         ┆ dicti      ┆ dicti      ┆ die        ┆ … ┆ dd.;  ┆ dd.; dicti ┆ null  ┆ null       │
│             ┆ (Plural)   ┆ (Plural)   ┆ genannten  ┆   ┆ dicti ┆            ┆       ┆            │
│ SS.         ┆ sancti     ┆ sancti     ┆ die        ┆ … ┆ null  ┆ null       ┆ null  ┆ null       │
│             ┆ (Plural)   ┆ (Plural)   ┆ heiligen   ┆   ┆       ┆            ┆       ┆            │
│ ss.         ┆ sancti     ┆ sancti     ┆ die        ┆ … ┆ ss.   ┆ ss.        ┆ null  ┆ null       │
│             ┆ (Plural)   ┆ (Plural)   ┆ heiligen   ┆   ┆       ┆            ┆       ┆            │
└─────────────┴────────────┴────────────┴────────────┴───┴───────┴────────────┴───────┴────────────┘

entries to ignore

In [12]:
lotta_abb.filter(pl.col("full_word").str.contains(r"\?"))

shape: (11, 18)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────┬───────┐
│ abbreviatio ┆ full_word   ┆ full_word_ ┆ translatio ┆ … ┆ RG8        ┆ RG9       ┆ note1 ┆ note2 │
│ n           ┆ ---         ┆ right      ┆ n          ┆   ┆ ---        ┆ ---       ┆ ---   ┆ ---   │
│ ---         ┆ str         ┆ ---        ┆ ---        ┆   ┆ str        ┆ str       ┆ str   ┆ str   │
│ str         ┆             ┆ str        ┆ str        ┆   ┆            ┆           ┆       ┆       │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════╪═══════╡
│ Arm.        ┆ ?           ┆ ?          ┆ null       ┆ … ┆ Arm.       ┆ Arm.      ┆ null  ┆ null  │
│ cath.       ┆ catholicus  ┆ catholicus ┆ null       ┆ … ┆ null       ┆ null      ┆ null  ┆ null  │
│             ┆ ?           ┆ ?          ┆            ┆   ┆            ┆           ┆       ┆       │
│ compon.     ┆ componere?  ┆ componere? ┆ null       ┆ … ┆ null       ┆ null      ┆ null  ┆ null  │
│ cont.       ┆ ?           ┆ ?          ┆ null       ┆ … ┆ null       ┆ null      ┆ null  ┆ null  │
│ ed.         ┆ ediert ?    ┆ ediert ?   ┆ null       ┆ … ┆ null       ┆ null      ┆ null  ┆ null  │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …     ┆ …     │
│ except.     ┆ exceptus ?  ┆ exceptus ? ┆ null       ┆ … ┆ null       ┆ null      ┆ null  ┆ null  │
│ pend.       ┆ ?           ┆ ?          ┆ null       ┆ … ┆ null       ┆ null      ┆ null  ┆ null  │
│ t. gr.      ┆ ?           ┆ ?          ┆ null       ┆ … ┆ null       ┆ null      ┆ null  ┆ null  │
│ tab. off.   ┆ tabellionat ┆ tabelliona ┆ null       ┆ … ┆ tab. off.; ┆ off. tab. ┆ null  ┆ null  │
│             ┆ us officium ┆ tus        ┆            ┆   ┆ off. tab.  ┆           ┆       ┆       │
│             ┆ ?           ┆ officium ? ┆            ┆   ┆            ┆           ┆       ┆       │
│ tabell.     ┆ tabellionat ┆ tabelliona ┆ null       ┆ … ┆ null       ┆ null      ┆ null  ┆ null  │
│ off.        ┆ us officium ┆ tus        ┆            ┆   ┆            ┆           ┆       ┆       │
│             ┆ ?           ┆ officium ? ┆            ┆   ┆            ┆           ┆       ┆       │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────┴───────┘

In [ ]:
def eq_or_None(abb, alt_abbs):
    comps = []
    for alt_abb in alt_abbs:
        comparison = abb == alt_abb
        comparison.fill_null(True)
        comps.append(comparison)

    return pl.all_horizontal(comps)

# TODO: doesn't work when (all) columns are null - why?
lotta_abb.filter(eq_or_None(pl.col("abbreviation"), [pl.col("RG1"), pl.col("RG2"), pl.col("RG3"), pl.col("RG4"), pl.col("RG5"), pl.col("RG6"), pl.col("RG7"), pl.col("RG8"), pl.col("RG9")]))

shape: (16, 18)
┌──────────────┬─────────────┬─────────────┬─────────────┬───┬──────────┬──────────┬───────┬───────┐
│ abbreviation ┆ full_word   ┆ full_word_r ┆ translation ┆ … ┆ RG8      ┆ RG9      ┆ note1 ┆ note2 │
│ ---          ┆ ---         ┆ ight        ┆ ---         ┆   ┆ ---      ┆ ---      ┆ ---   ┆ ---   │
│ str          ┆ str         ┆ ---         ┆ str         ┆   ┆ str      ┆ str      ┆ str   ┆ str   │
│              ┆             ┆ str         ┆             ┆   ┆          ┆          ┆       ┆       │
╞══════════════╪═════════════╪═════════════╪═════════════╪═══╪══════════╪══════════╪═══════╪═══════╡
│ bb.          ┆ beati       ┆ beati       ┆ die         ┆ … ┆ bb.      ┆ bb.      ┆ null  ┆ null  │
│              ┆ (Plural)    ┆ (Plural)    ┆ heiligen    ┆   ┆          ┆          ┆       ┆       │
│ ian.         ┆ ianuarius   ┆ ianuarius   ┆ Januar      ┆ … ┆ ian.     ┆ ian.     ┆ null  ┆ null  │
│ iul.         ┆ iulius      ┆ iulius      ┆ Juli        ┆ … ┆ iul.     ┆ iul.     ┆ null  ┆ null  │
│ leg.         ┆ leges       ┆ leges       ┆ Rechte      ┆ … ┆ leg.     ┆ leg.     ┆ null  ┆ null  │
│ mag.         ┆ magister    ┆ magister    ┆ Magister,   ┆ … ┆ mag.     ┆ mag.     ┆ null  ┆ null  │
│              ┆             ┆             ┆ Meister,    ┆   ┆          ┆          ┆       ┆       │
│              ┆             ┆             ┆ Vorsteher   ┆   ┆          ┆          ┆       ┆       │
│ …            ┆ …           ┆ …           ┆ …           ┆ … ┆ …        ┆ …        ┆ …     ┆ …     │
│ prep.        ┆ prepositus  ┆ prepositus  ┆ Propst,     ┆ … ┆ prep.    ┆ prep.    ┆ null  ┆ null  │
│              ┆             ┆             ┆ Vorsteher   ┆   ┆          ┆          ┆       ┆       │
│ presb.       ┆ presbiter   ┆ presbiter   ┆ Priester    ┆ … ┆ presb.   ┆ presb.   ┆ null  ┆ null  │
│ sept.        ┆ september   ┆ september   ┆ September   ┆ … ┆ sept.    ┆ sept.    ┆ null  ┆ null  │
│ subdiac.     ┆ subdiaconus ┆ subdiaconus ┆ Subdiakon   ┆ … ┆ subdiac. ┆ subdiac. ┆ null  ┆ null  │
│ theol.       ┆ theologia   ┆ theologia   ┆ Theologie   ┆ … ┆ theol.   ┆ theol.   ┆ null  ┆ null  │
└──────────────┴─────────────┴─────────────┴─────────────┴───┴──────────┴──────────┴───────┴───────┘

In [51]:
lotta_abb.filter(pl.all_horizontal(pl.col("RG1").is_null(), pl.col("RG2").is_null(), pl.col("RG3").is_null(), pl.col("RG4").is_null(), pl.col("RG5").is_null(), pl.col("RG6").is_null(), pl.col("RG7").is_null(), pl.col("RG8").is_null(), pl.col("RG9").is_null()))

shape: (166, 18)
┌────────────────┬───────────────┬───────────────┬───────────────┬───┬──────┬──────┬───────┬───────┐
│ abbreviation   ┆ full_word     ┆ full_word_rig ┆ translation   ┆ … ┆ RG8  ┆ RG9  ┆ note1 ┆ note2 │
│ ---            ┆ ---           ┆ ht            ┆ ---           ┆   ┆ ---  ┆ ---  ┆ ---   ┆ ---   │
│ str            ┆ str           ┆ ---           ┆ str           ┆   ┆ str  ┆ str  ┆ str   ┆ str   │
│                ┆               ┆ str           ┆               ┆   ┆      ┆      ┆       ┆       │
╞════════════════╪═══════════════╪═══════════════╪═══════════════╪═══╪══════╪══════╪═══════╪═══════╡
│ abb. et. conv. ┆ abbas et      ┆ abbas et      ┆ Abt und       ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│                ┆ conventus     ┆ conventus     ┆ Konvent       ┆   ┆      ┆      ┆       ┆       │
│ abbr.          ┆ litterarum    ┆ litterarum    ┆ Abbreviator,  ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│                ┆ apostolicarum ┆ apostolicarum ┆ Abfasser von  ┆   ┆      ┆      ┆       ┆       │
│                ┆ abbre…        ┆ abbre…        ┆ Konz…         ┆   ┆      ┆      ┆       ┆       │
│ absolv.        ┆ absolvere     ┆ absolvere     ┆ lossprechen   ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│ accip.         ┆ accipere      ┆ accipere      ┆ empfangen,    ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│                ┆               ┆               ┆ erhalten      ┆   ┆      ┆      ┆       ┆       │
│ adher.         ┆ adherens;     ┆ adherens;     ┆ null          ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│                ┆ adherentes    ┆ adherentes    ┆               ┆   ┆      ┆      ┆       ┆       │
│ …              ┆ …             ┆ …             ┆ …             ┆ … ┆ …    ┆ …    ┆ …     ┆ …     │
│ tabell. off.   ┆ tabellionatus ┆ tabellionatus ┆ null          ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│                ┆ officium ?    ┆ officium ?    ┆               ┆   ┆      ┆      ┆       ┆       │
│ transfer.      ┆ transferre    ┆ transferre    ┆ null          ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│ Tur.           ┆ Turonensis    ┆ Turonensis    ┆ Turnosen      ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│                ┆               ┆               ┆ (Münze)       ┆   ┆      ┆      ┆       ┆       │
│ univers.       ┆ universitas   ┆ universitas   ┆ Universität,  ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│                ┆               ┆               ┆ Gesamtheit    ┆   ┆      ┆      ┆       ┆       │
│                ┆               ┆               ┆ (der B…       ┆   ┆      ┆      ┆       ┆       │
│ universit.     ┆ universitas   ┆ universitas   ┆ Universität,  ┆ … ┆ null ┆ null ┆ null  ┆ null  │
│                ┆               ┆               ┆ Gesamtheit    ┆   ┆      ┆      ┆       ┆       │
│                ┆               ┆               ┆ (der B…       ┆   ┆      ┆      ┆       ┆       │
└────────────────┴───────────────┴───────────────┴───────────────┴───┴──────┴──────┴───────┴───────┘

In [22]:
import polars as pl
import polars.selectors as cs
alias = pl.read_csv("transformed/aliases.csv")
manual = pl.read_csv("data/manually_revised_abbreviations.csv", row_index_name="index", row_index_offset=1)

In [25]:
siehe = manual.filter(pl.any_horizontal(cs.string().str.contains("siehe", literal=True)))
siehe.join(alias, left_on="index", right_on="source_row_id", how="anti")

shape: (17, 18)
┌───────┬───────────┬───────────────┬──────────────┬───┬──────┬──────┬──────────────┬──────────────┐
│ index ┆ Abkürzung ┆ Auflösung     ┆ Übersetzung  ┆ … ┆ RG8  ┆ RG9  ┆ Bemerkungen  ┆ Bemerkungen_ │
│ ---   ┆ ---       ┆ ---           ┆ ---          ┆   ┆ ---  ┆ ---  ┆ ---          ┆ duplicated_0 │
│ u32   ┆ str       ┆ str           ┆ str          ┆   ┆ str  ┆ str  ┆ str          ┆ ---          │
│       ┆           ┆               ┆              ┆   ┆      ┆      ┆              ┆ str          │
╞═══════╪═══════════╪═══════════════╪══════════════╪═══╪══════╪══════╪══════════════╪══════════════╡
│ 76    ┆ arg.      ┆ argentum      ┆ Silber       ┆ … ┆ arg. ┆ arg. ┆ null         ┆ nicht in Bd. │
│       ┆           ┆               ┆              ┆   ┆      ┆      ┆              ┆ 1, 2, 3; in  │
│       ┆           ┆               ┆              ┆   ┆      ┆      ┆              ┆ Bd. 4…       │
│ 92    ┆ null      ┆ bulla         ┆ Bulle        ┆ … ┆ null ┆ null ┆ null         ┆ null         │
│ 181   ┆ null      ┆ communis      ┆ gewöhnlich   ┆ … ┆ null ┆ null ┆ null         ┆ null         │
│ 194   ┆ comp.     ┆ competenter   ┆ angemessen,  ┆ … ┆ null ┆ null ┆ null         ┆ null         │
│       ┆           ┆               ┆ befriedigend ┆   ┆      ┆      ┆              ┆              │
│ 219   ┆ null      ┆ consanguinita ┆ (Bluts-)verw ┆ … ┆ null ┆ null ┆ null         ┆ null         │
│       ┆           ┆ s             ┆ andtschaft   ┆   ┆      ┆      ┆              ┆              │
│ …     ┆ …         ┆ …             ┆ …            ┆ … ┆ …    ┆ …    ┆ …            ┆ …            │
│ 962   ┆ null      ┆ ?             ┆ null         ┆ … ┆ null ┆ null ┆ null         ┆ null         │
│ 975   ┆ null      ┆ testimonialis ┆ null         ┆ … ┆ null ┆ null ┆ null         ┆ null         │
│ 990   ┆ translat. ┆ translaturus  ┆ null         ┆ … ┆ null ┆ null ┆ in 6 nicht   ┆ null         │
│       ┆           ┆               ┆              ┆   ┆      ┆      ┆ verwendet;   ┆              │
│       ┆           ┆               ┆              ┆   ┆      ┆      ┆ aber vie…    ┆              │
│ 1006  ┆ v.        ┆ virgo;        ┆ null         ┆ … ┆ null ┆ null ┆ null         ┆ null         │
│ 1007  ┆ null      ┆ vide          ┆ null         ┆ … ┆ null ┆ null ┆ null         ┆ null         │
└───────┴───────────┴───────────────┴──────────────┴───┴──────┴──────┴──────────────┴──────────────┘