Steps:

0. strip whitespace for the Abkürzung and Auflösung columns
1. make the inheriting of abbreviations explicit
    - The first column value is inherited from the last line that had a value in column 1.
2. transform so that each row only contains it's own abbreviation value in it's RG1 to RG9 columns
    1. this is only done for rows that only contain abbreviations or their own expansion in the RG columns. Rows where this doesn't hold, are often ones where it's unclear what the abbreviation actually stands for. For these, special handling will be necessary.
    2. information 
3. check whether abbreviations actually occur in the RG text
    1. keep only rows with abbreviations that do occur
    3. note abbreviations that don't occur exactly, but where something similar occurs
4. note in which volumes abbreviations occur

## step 0

In [ ]:
import polars as pl
pl.read_csv("data/abbreviations.csv").with_columns(
    pl.col("Abkürzung").str.strip_chars().alias("Abkürzung"),
    pl.col("Auflösung").str.strip_chars().alias("Auflösung"),
    ).write_csv("data/abbreviations_wo_whitespace.csv")

## step 1

In [1]:
import csv

input_file = 'data/abbreviations_wo_whitespace.csv'
output_file = 'data/explicit_abbreviations.csv'

last_value = ''

with open(input_file, 'r', encoding='utf-8') as infile, open(output_file, 'w', encoding='utf-8', newline='') as outfile:
    reader = csv.reader(infile)
    writer = csv.writer(outfile)
    
    # Write header as-is
    header = next(reader)
    writer.writerow(header)
    
    for row in reader:
        if row[0].strip():  # If first column has a value
            row[0] = row[0].strip() # remove whitespace
            last_value = row[0]
        else:  # Inherit from last non-empty value
            row[0] = last_value
        writer.writerow(row)

In [2]:
import polars as pl

explicit = pl.read_csv("data/explicit_abbreviations.csv")
explicit.sort(by=[pl.col("Abkürzung").str.to_lowercase(), pl.col("Auflösung")]).write_csv("data/explicit_abbreviations.csv")

## step 2

In [3]:
from process_abbreviations import process_csv

input_file = 'data/explicit_abbreviations.csv'
output_file = 'data/processed_abbreviations.csv'

process_csv(input_file, output_file)

sorting afterwards was simpler

In [4]:
processed = pl.read_csv("data/processed_abbreviations.csv")
processed.sort(by=[pl.col("Abkürzung").str.to_lowercase(), pl.col("Auflösung")]).write_csv("data/processed_abbreviations.csv")

## step 3

In [5]:
text = pl.read_csv("data/RG_header_sublemma_all.csv")
text = text.with_columns(
    pl.coalesce([pl.col("header_no_tags"), pl.col("sublemma_no_tags")]).alias("text")
    #pl.col("volume").cast(pl.String)
).select(["volume", "text"])

abbr = pl.read_csv("data/processed_abbreviations.csv")

In [6]:
def search(text, query, literal=False, show=True) -> tuple[bool, str]:
    """
    returns a tuple: (whether the query exists at all in the RG, in which volumes it exists)
    """
    result = text.filter(pl.col("text").str.contains(query, literal=literal)).group_by("volume").len().sort("volume")
    total = result.select(pl.col("len").sum()).item()
    if(show):
        display(result)
        print(f"Total: {total}")

    s = ""
    for x in result.get_column("volume").to_list():
        s+= str(x) + '|'
    s = s[:-1]
    
    return total > 0, s

In [7]:
abbr.filter(~pl.col("Abkürzung").str.ends_with("."))

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Abkürzung ┆ Auflösung ┆ Übersetzu ┆ Anmerkung ┆ … ┆ RG8       ┆ RG9       ┆ Bemerkung ┆ Bemerkun │
│ ---       ┆ ---       ┆ ng        ┆ en        ┆   ┆ ---       ┆ ---       ┆ en_1      ┆ gen_2    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ def. nat. ┆ defectus  ┆ Geburtsma ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ (c. c.)   ┆ natalium  ┆ kel (von  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (de       ┆ einem     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ coniugat… ┆ Verhei…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ def. nat. ┆ defectus  ┆ Geburtsma ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ (c. s.)   ┆ natalium  ┆ kel (von  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (de       ┆ einem     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ coniugat… ┆ Verhei…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ def. nat. ┆ defectus  ┆ Geburtsma ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ (p. c.)   ┆ natalium  ┆ kel (von  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (de       ┆ einem     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ presbite… ┆ Priest…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ def. nat. ┆ defectus  ┆ Geburtsma ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ (p. s.)   ┆ natalium  ┆ kel (von  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (de       ┆ einem     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ presbite… ┆ Priest…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ def. nat. ┆ defectus  ┆ Geburtsma ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ (s. c.)   ┆ natalium  ┆ kel (von  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (de       ┆ einem     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ soluto e… ┆ Ledige…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ def. nat. ┆ defectus  ┆ Geburtsma ┆ null      ┆ … ┆ null      ┆ null      ┆ alle Komb ┆ null     │
│ (s. s.)   ┆ natalium  ┆ kel (von  ┆           ┆   ┆           ┆           ┆ inationen ┆          │
│           ┆ (de       ┆ einem     ┆           ┆   ┆           ┆           ┆ mit def.  ┆          │
│           ┆ soluto e… ┆ Ledige…   ┆           ┆   ┆           ┆           ┆ na…       ┆          │
│ hosp.     ┆ hospitale ┆ null      ┆ null      ┆ … ┆ hosp.     ┆ hosp.     ┆ null      ┆ null     │
│ pauperum  ┆ pauperum  ┆           ┆           ┆   ┆ pauperum  ┆ pauperum  ┆           ┆          │
│ o. s.     ┆ ordo      ┆ Klarissen ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ Clare     ┆ sancte    ┆ orden     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Clare     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Rom.      ┆ Romana    ┆ null      ┆ 1         ┆ … ┆ Romana    ┆ Romana    ┆ null      ┆ null     │
│ curia     ┆ curia     ┆           ┆           ┆   ┆ cur.      ┆ cur.;     ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ cur.      ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Romana    ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
import re

def construct_query(abbreviation):
    escaped = re.escape(abbreviation)
    escaped = escaped.replace(r'\.', r'\.?')
    if escaped.endswith(r'\.?'):
        escaped = escaped[:-3] + r'[\., ]'
    return r'[^\w]' + escaped

In [9]:
abbr = abbr.with_columns(
    # `.` seems to sometimes be missing (or at least it's likely), so we don't match literally, but with `.` optionally missing
    #pl.col("Abkürzung").map_elements(lambda x: search(text, x, literal=True, show=False)[0]).alias("exists"),
    pl.col("Abkürzung").map_elements(lambda x: search(text, construct_query(x), literal=False, show=False)[0]).alias("exists"),
    pl.col("Abkürzung").map_elements(lambda x: search(text, re.escape(x[:-1]) + "[^a-zA-Z]", literal=False, show=False)[0]).alias("exists_similar"),
    pl.col("Abkürzung").map_elements(lambda x: search(text, "(" + "|".join(re.escape(x).split(r"\ ")) + ")", literal=False, show=False)[0], pl.Boolean).alias("part_exists")
)
abbr

shape: (1_288, 20)
┌───────────┬────────────┬────────────┬───────────┬───┬───────────┬────────┬───────────┬───────────┐
│ Abkürzung ┆ Auflösung  ┆ Übersetzun ┆ Anmerkung ┆ … ┆ Bemerkung ┆ exists ┆ exists_si ┆ part_exis │
│ ---       ┆ ---        ┆ g          ┆ en        ┆   ┆ en_2      ┆ ---    ┆ milar     ┆ ts        │
│ str       ┆ str        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ bool   ┆ ---       ┆ ---       │
│           ┆            ┆ str        ┆ str       ┆   ┆ str       ┆        ┆ bool      ┆ bool      │
╞═══════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ a.        ┆ ?          ┆ null       ┆ null      ┆ … ┆ (Bd. II   ┆ true   ┆ true      ┆ true      │
│           ┆            ┆            ┆           ┆   ┆ 25)       ┆        ┆           ┆           │
│ a.        ┆ annus      ┆ Jahr       ┆ siehe     ┆ … ┆ null      ┆ true   ┆ true      ┆ true      │
│           ┆            ┆            ┆ Eintrag   ┆   ┆           ┆        ┆           ┆           │
│           ┆            ┆            ┆ "an."     ┆   ┆           ┆        ┆           ┆           │
│ a.        ┆ annus      ┆ Jahr       ┆ null      ┆ … ┆ null      ┆ true   ┆ true      ┆ true      │
│ a.        ┆ argentum   ┆ Silber     ┆ null      ┆ … ┆ meist in  ┆ true   ┆ true      ┆ true      │
│           ┆            ┆            ┆           ┆   ┆ Verbindun ┆        ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ g m. a.   ┆        ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ p.; …     ┆        ┆           ┆           │
│ abb.      ┆ abbas      ┆ Abt        ┆ null      ┆ … ┆ null      ┆ true   ┆ true      ┆ true      │
│ …         ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …      ┆ …         ┆ …         │
│ vig.      ┆ vigore     ┆ kraft      ┆ vigor in  ┆ … ┆ null      ┆ true   ┆ true      ┆ true      │
│           ┆            ┆            ┆ Bd. 6,8   ┆   ┆           ┆        ┆           ┆           │
│ virg.     ┆ virgo      ┆ Jungfrau   ┆ in 4 auch ┆ … ┆ null      ┆ true   ┆ true      ┆ true      │
│           ┆            ┆            ┆ v.        ┆   ┆           ┆        ┆           ┆           │
│ visit.    ┆ visitare;  ┆ besuchen;  ┆ null      ┆ … ┆ null      ┆ true   ┆ true      ┆ true      │
│           ┆            ┆ kontrollie ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆            ┆ ren;       ┆           ┆   ┆           ┆        ┆           ┆           │
│ visit.    ┆ visitatio  ┆ Besuch;    ┆ null      ┆ … ┆ null      ┆ true   ┆ true      ┆ true      │
│           ┆            ┆ Rechenscha ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆            ┆ ftslegung  ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆            ┆ de…        ┆           ┆   ┆           ┆        ┆           ┆           │
│ vulg.     ┆ vulgariter ┆ gewöhnlich ┆ null      ┆ … ┆ null      ┆ true   ┆ true      ┆ true      │
│           ┆            ┆ , sonst;   ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆            ┆ in der     ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆            ┆ Volk…      ┆           ┆   ┆           ┆        ┆           ┆           │
└───────────┴────────────┴────────────┴───────────┴───┴───────────┴────────┴───────────┴───────────┘

In [10]:
with pl.Config(tbl_rows=-1):
    display(abbr.filter((pl.col("exists") == False) & (pl.col("exists_similar") == True)).get_column("Abkürzung").unique().sort())

shape: (21,)
Series: 'Abkürzung' [str]
[
	"Ap."
	"camerar."
	"confirm."
	"dict."
	"flor."
	"imp."
	"k."
	"laci."
	"obs."
	"occ."
	"perc."
	"poss."
	"r. b."
	"rec."
	"rest."
	"s. R. e."
	"s. p. d."
	"sac."
	"sing."
	"t. gr."
	"thesaurar."
]

In [11]:
#with pl.Config(tbl_rows=-1):
    #display(abbr.filter((pl.col("part_exists") == True) & (pl.col("exists") == False)))
abbr.filter((pl.col("part_exists") == True) & (pl.col("exists") == False))

shape: (64, 20)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬────────┬───────────┬───────────┐
│ Abkürzung  ┆ Auflösung  ┆ Übersetzu ┆ Anmerkung ┆ … ┆ Bemerkung ┆ exists ┆ exists_si ┆ part_exis │
│ ---        ┆ ---        ┆ ng        ┆ en        ┆   ┆ en_2      ┆ ---    ┆ milar     ┆ ts        │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool   ┆ ---       ┆ ---       │
│            ┆            ┆ str       ┆ str       ┆   ┆ str       ┆        ┆ bool      ┆ bool      │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ ben. c. c. ┆ beneficium ┆ Pfründe   ┆ siehe     ┆ … ┆ null      ┆ false  ┆ false     ┆ true      │
│            ┆ cum cura   ┆ mit       ┆ benef. c. ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ Seelsorge ┆ c.        ┆   ┆           ┆        ┆           ┆           │
│ ben. c. c. ┆ beneficium ┆ Pfründe   ┆ null      ┆ … ┆ null      ┆ false  ┆ false     ┆ true      │
│            ┆ cum cura   ┆ mit       ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ Seelsorge ┆           ┆   ┆           ┆        ┆           ┆           │
│ ben. s. c. ┆ beneficium ┆ Pfründe   ┆ siehe     ┆ … ┆ null      ┆ false  ┆ false     ┆ true      │
│            ┆ sine cura  ┆ ohne      ┆ benef s.  ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ Seelsorge ┆ c.        ┆   ┆           ┆        ┆           ┆           │
│ ben. s. c. ┆ beneficium ┆ Pfründe   ┆ null      ┆ … ┆ null      ┆ false  ┆ false     ┆ true      │
│            ┆ sine cura  ┆ ohne      ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ Seelsorge ┆           ┆   ┆           ┆        ┆           ┆           │
│ camerar.   ┆ camerarius ┆ Kämmerer  ┆ null      ┆ … ┆ null      ┆ false  ┆ true      ┆ true      │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …      ┆ …         ┆ …         │
│ testim.    ┆ testimonia ┆ Bescheini ┆ null      ┆ … ┆ null      ┆ false  ┆ false     ┆ true      │
│ litt.      ┆ les        ┆ gung,     ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆ littere    ┆ Zeugnis   ┆           ┆   ┆           ┆        ┆           ┆           │
│ thesaurar. ┆ thesaurari ┆ Amt des   ┆ null      ┆ … ┆ null      ┆ false  ┆ true      ┆ true      │
│            ┆ a          ┆ Thesaurar ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ s         ┆           ┆   ┆           ┆        ┆           ┆           │
│ thesaurar. ┆ thesaurari ┆ Amt des   ┆ null      ┆ … ┆ null      ┆ false  ┆ true      ┆ true      │
│            ┆ a          ┆ Thesaurar ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ s         ┆           ┆   ┆           ┆        ┆           ┆           │
│ thesaurar. ┆ thesaurari ┆ Amt des   ┆ null      ┆ … ┆ null      ┆ false  ┆ true      ┆ true      │
│            ┆ us         ┆ Thesaurar ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ s, Schatz ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ meis…     ┆           ┆   ┆           ┆        ┆           ┆           │
│ thesaurar. ┆ thesaurari ┆ Amt des   ┆ siehe     ┆ … ┆ null      ┆ false  ┆ true      ┆ true      │
│            ┆ us         ┆ Thesaurar ┆ thes. und ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ s, Schatz ┆ thesaur.  ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ meis…     ┆           ┆   ┆           ┆        ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴────────┴───────────┴───────────┘

In [12]:
abbr.filter(pl.col("exists") == False).get_column("Abkürzung").unique()

shape: (122,)
Series: 'Abkürzung' [str]
[
	"penitent."
	"protomart."
	"sac."
	"pecun."
	"s. p. d."
	…
	"privileg."
	"confirm."
	"referend."
	"laical."
	"pontif."
]

In [13]:
abbr.filter(pl.col("exists") == True).drop("exists", "exists_similar", "part_exists").write_csv("data/abbreviations_with_matches.csv")

In [14]:
construct_query("thesaurar.")

'[^\\w]thesaurar[\\., ]'

In [15]:
abbr.filter(pl.col("Abkürzung").str.contains("thesaurar"))

shape: (4, 20)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬────────┬───────────┬───────────┐
│ Abkürzung  ┆ Auflösung  ┆ Übersetzu ┆ Anmerkung ┆ … ┆ Bemerkung ┆ exists ┆ exists_si ┆ part_exis │
│ ---        ┆ ---        ┆ ng        ┆ en        ┆   ┆ en_2      ┆ ---    ┆ milar     ┆ ts        │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool   ┆ ---       ┆ ---       │
│            ┆            ┆ str       ┆ str       ┆   ┆ str       ┆        ┆ bool      ┆ bool      │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ thesaurar. ┆ thesaurari ┆ Amt des   ┆ null      ┆ … ┆ null      ┆ false  ┆ true      ┆ true      │
│            ┆ a          ┆ Thesaurar ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ s         ┆           ┆   ┆           ┆        ┆           ┆           │
│ thesaurar. ┆ thesaurari ┆ Amt des   ┆ null      ┆ … ┆ null      ┆ false  ┆ true      ┆ true      │
│            ┆ a          ┆ Thesaurar ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ s         ┆           ┆   ┆           ┆        ┆           ┆           │
│ thesaurar. ┆ thesaurari ┆ Amt des   ┆ null      ┆ … ┆ null      ┆ false  ┆ true      ┆ true      │
│            ┆ us         ┆ Thesaurar ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ s, Schatz ┆           ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ meis…     ┆           ┆   ┆           ┆        ┆           ┆           │
│ thesaurar. ┆ thesaurari ┆ Amt des   ┆ siehe     ┆ … ┆ null      ┆ false  ┆ true      ┆ true      │
│            ┆ us         ┆ Thesaurar ┆ thes. und ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ s, Schatz ┆ thesaur.  ┆   ┆           ┆        ┆           ┆           │
│            ┆            ┆ meis…     ┆           ┆   ┆           ┆        ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴────────┴───────────┴───────────┘

## step 4

In [16]:
existing = pl.read_csv("data/abbreviations_with_matches.csv")
existing = existing.with_columns(
    #pl.col("Abkürzung").map_elements(lambda x: search(text, re.escape(x).replace(r'\.', r'\.?'), literal=False, show=False)[1]).alias("volumes")
    pl.col("Abkürzung").map_elements(lambda x: search(text, construct_query(x), literal=False, show=False)[1]).alias("volumes"),
)
existing

shape: (1_061, 18)
┌───────────┬────────────┬────────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ Abkürzung ┆ Auflösung  ┆ Übersetzun ┆ Anmerkung ┆ … ┆ RG9    ┆ Bemerkung ┆ Bemerkung ┆ volumes   │
│ ---       ┆ ---        ┆ g          ┆ en        ┆   ┆ ---    ┆ en_1      ┆ en_2      ┆ ---       │
│ str       ┆ str        ┆ ---        ┆ ---       ┆   ┆ str    ┆ ---       ┆ ---       ┆ str       │
│           ┆            ┆ str        ┆ str       ┆   ┆        ┆ str       ┆ str       ┆           │
╞═══════════╪════════════╪════════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ a.        ┆ ?          ┆ null       ┆ null      ┆ … ┆ null   ┆ null      ┆ (Bd. II   ┆ 1|2|3|4|5 │
│           ┆            ┆            ┆           ┆   ┆        ┆           ┆ 25)       ┆ |6|7|8|9| │
│           ┆            ┆            ┆           ┆   ┆        ┆           ┆           ┆ 10        │
│ a.        ┆ annus      ┆ Jahr       ┆ siehe     ┆ … ┆ null   ┆ null      ┆ null      ┆ 1|2|3|4|5 │
│           ┆            ┆            ┆ Eintrag   ┆   ┆        ┆           ┆           ┆ |6|7|8|9| │
│           ┆            ┆            ┆ "an."     ┆   ┆        ┆           ┆           ┆ 10        │
│ a.        ┆ annus      ┆ Jahr       ┆ null      ┆ … ┆ null   ┆ null      ┆ null      ┆ 1|2|3|4|5 │
│           ┆            ┆            ┆           ┆   ┆        ┆           ┆           ┆ |6|7|8|9| │
│           ┆            ┆            ┆           ┆   ┆        ┆           ┆           ┆ 10        │
│ a.        ┆ argentum   ┆ Silber     ┆ null      ┆ … ┆ a.     ┆ null      ┆ meist in  ┆ 1|2|3|4|5 │
│           ┆            ┆            ┆           ┆   ┆        ┆           ┆ Verbindun ┆ |6|7|8|9| │
│           ┆            ┆            ┆           ┆   ┆        ┆           ┆ g m. a.   ┆ 10        │
│           ┆            ┆            ┆           ┆   ┆        ┆           ┆ p.; …     ┆           │
│ abb.      ┆ abbas      ┆ Abt        ┆ null      ┆ … ┆ abb.   ┆ null      ┆ null      ┆ 1|2|3|4|5 │
│           ┆            ┆            ┆           ┆   ┆        ┆           ┆           ┆ |6|7|8|9| │
│           ┆            ┆            ┆           ┆   ┆        ┆           ┆           ┆ 10        │
│ …         ┆ …          ┆ …          ┆ …         ┆ … ┆ …      ┆ …         ┆ …         ┆ …         │
│ vig.      ┆ vigore     ┆ kraft      ┆ vigor in  ┆ … ┆ vig.   ┆ null      ┆ null      ┆ 5|6|7|8|9 │
│           ┆            ┆            ┆ Bd. 6,8   ┆   ┆        ┆           ┆           ┆ |10       │
│ virg.     ┆ virgo      ┆ Jungfrau   ┆ in 4 auch ┆ … ┆ virg.  ┆ null      ┆ null      ┆ 1|2|4|5|6 │
│           ┆            ┆            ┆ v.        ┆   ┆        ┆           ┆           ┆ |7|8|9|10 │
│ visit.    ┆ visitare;  ┆ besuchen;  ┆ null      ┆ … ┆ visit. ┆ null      ┆ null      ┆ 1|2|4|5|6 │
│           ┆            ┆ kontrollie ┆           ┆   ┆        ┆           ┆           ┆ |7|8|9|10 │
│           ┆            ┆ ren;       ┆           ┆   ┆        ┆           ┆           ┆           │
│ visit.    ┆ visitatio  ┆ Besuch;    ┆ null      ┆ … ┆ null   ┆ null      ┆ null      ┆ 1|2|4|5|6 │
│           ┆            ┆ Rechenscha ┆           ┆   ┆        ┆           ┆           ┆ |7|8|9|10 │
│           ┆            ┆ ftslegung  ┆           ┆   ┆        ┆           ┆           ┆           │
│           ┆            ┆ de…        ┆           ┆   ┆        ┆           ┆           ┆           │
│ vulg.     ┆ vulgariter ┆ gewöhnlich ┆ null      ┆ … ┆ vulg.  ┆ null      ┆ null      ┆ 1|2|3|4|5 │
│           ┆            ┆ , sonst;   ┆           ┆   ┆        ┆           ┆           ┆ |6|7|8|9| │
│           ┆            ┆ in der     ┆           ┆   ┆        ┆           ┆           ┆ 10        │
│           ┆            ┆ Volk…      ┆           ┆   ┆        ┆           ┆           ┆           │
└───────────┴────────────┴────────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

In [17]:
existing.filter(
    pl.any_horizontal(
        pl.col(f"RG{i}").is_not_null() & (~pl.col("volumes").str.contains(f"{i}"))
        for i in range(1, 10)
    )
)

shape: (118, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Abkürzung ┆ Auflösung ┆ Übersetzu ┆ Anmerkung ┆ … ┆ RG9       ┆ Bemerkung ┆ Bemerkung ┆ volumes  │
│ ---       ┆ ---       ┆ ng        ┆ en        ┆   ┆ ---       ┆ en_1      ┆ en_2      ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ abb. et.  ┆ abbas et  ┆ Abt und   ┆ null      ┆ … ┆ abb. et.  ┆ null      ┆ null      ┆ 1|3|5|9| │
│ conv.     ┆ conventus ┆ Konvent   ┆           ┆   ┆ conv.     ┆           ┆           ┆ 10       │
│ abol.     ┆ abolere;  ┆ tilgen;   ┆ null      ┆ … ┆ abol.;    ┆ null      ┆ null      ┆ 3|6|7|8| │
│           ┆           ┆ abschaffe ┆           ┆   ┆ abolire   ┆           ┆           ┆ 9|10     │
│           ┆           ┆ n;        ┆           ┆   ┆           ┆           ┆           ┆          │
│ acc.      ┆ accipere  ┆ empfangen ┆ null      ┆ … ┆ acc.; acc ┆ null      ┆ null      ┆ 2|4|5|6| │
│           ┆           ┆ ,         ┆           ┆   ┆ eptare;   ┆           ┆           ┆ 7|8|9|10 │
│           ┆           ┆ erhalten  ┆           ┆   ┆ acceptati ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ o; a…     ┆           ┆           ┆          │
│ acol.     ┆ acolitus  ┆ Akoluth,  ┆ null      ┆ … ┆ acol.;    ┆ null      ┆ null      ┆ 2|4|5|6| │
│           ┆           ┆ Geistlich ┆           ┆   ┆ acolitus; ┆           ┆           ┆ 7|8|9|10 │
│           ┆           ┆ er mit    ┆           ┆   ┆ acolutus  ┆           ┆           ┆          │
│           ┆           ┆ der h…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ adh.      ┆ adherens; ┆ null      ┆ null      ┆ … ┆ adherens; ┆ null      ┆ null      ┆ 1        │
│           ┆ adherente ┆           ┆           ┆   ┆ adherente ┆           ┆           ┆          │
│           ┆ s         ┆           ┆           ┆   ┆ s         ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ testim.   ┆ testimoni ┆ null      ┆ in 4 auch ┆ … ┆ testim.   ┆ möglicher ┆ null      ┆ 9|10     │
│           ┆ alis      ┆           ┆ test.     ┆   ┆           ┆ weise     ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ auch in   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ anderen…  ┆           ┆          │
│ thes.     ┆ thesaurar ┆ Amt des   ┆ null      ┆ … ┆ thes.     ┆ nicht aus ┆ null      ┆ 10       │
│           ┆ ius       ┆ Thesaurar ┆           ┆   ┆           ┆ zuschließ ┆           ┆          │
│           ┆           ┆ s, Schatz ┆           ┆   ┆           ┆ en, dass  ┆           ┆          │
│           ┆           ┆ meis…     ┆           ┆   ┆           ┆ nic…      ┆           ┆          │
│ Tur.      ┆ Turonensi ┆ Turnosen  ┆ kommt aus ┆ … ┆ null      ┆ in Bd.    ┆ null      ┆ 5        │
│           ┆ s         ┆ (Münze)   ┆ geschrieb ┆   ┆           ┆ 1,2,3     ┆           ┆          │
│           ┆           ┆           ┆ en nicht  ┆   ┆           ┆ nicht ver ┆           ┆          │
│           ┆           ┆           ┆ vor       ┆   ┆           ┆ wendet, … ┆           ┆          │
│ unac.     ┆ unacum    ┆ zusammen  ┆ null      ┆ … ┆ unac.     ┆ null      ┆ null      ┆ 2|5|6|7| │
│           ┆           ┆ mit       ┆           ┆   ┆           ┆           ┆           ┆ 8|9|10   │
│ univers.  ┆ universit ┆ Universit ┆ univers.  ┆ … ┆ null      ┆ null      ┆ null      ┆ 5|8      │
│           ┆ as        ┆ ät, Gesam ┆ 5, 8; in  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ theit     ┆ 8 univ.   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ (der B…   ┆ nur …     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
existing.write_csv("data/abbreviations_with_volumes.csv")

## distinguish between simple and more complex cases

In [19]:
existing = pl.read_csv("data/abbreviations_with_volumes.csv")
complex_abbreviations = existing.filter(pl.any_horizontal(~(pl.col("^RG[1-9]$").is_null() | pl.col("Abkürzung").str.contains(pl.col("^RG[1-9]$")))) | pl.any_horizontal(pl.col("^Abkürzung|Auflösung|RG[1-9]$").str.contains(";"))).get_column("Abkürzung").unique().to_list()
existing.filter(~pl.col("Abkürzung").is_in(complex_abbreviations)).write_csv("data/simple.csv")
existing.filter(pl.col("Abkürzung").is_in(complex_abbreviations)).write_csv("data/complex.csv")